### ISSUE TITLE
More Flexibility for single star use

### ISSUE THREAD

**Issue by sjschmidt** [ekaterinailin/AltaiPony#37]
#### What needs to be created or improved?
The ability to run the fake flare injection procedure even for very unlikely flares. This would be useful in doing detailed studies of a single star or a handful of stars (but less so for large samples). 

#### What is the goal / expected behaviour?
Default use is the same, but keywords allow more choices around fake flare procedure for small flares.

**Comment by ekaterinailin** [comment]
This is doable now with `FLC.sample_flare_recovery` and its keywords now! See the [docs](https://altaipony.readthedocs.io/en/latest/tutorials/fakeflares.html) for an example. You can pick the `ampl` and `dur` ranges such that you inject only very small flares.
