### ISSUE TITLE
Can't open downloaded fits file

### ISSUE THREAD

**Issue by dPulsar** [ekaterinailin/AltaiPony#47]
#### What needs to be created or improved?

I'm having trouble opening a fits file downloaded from the Kepler database. However, the example fits file that was provided does work. 
#### Can you provide an example?

```python
from altaipony.flarelc import FlareLightCurve
from altaipony.lcio import from_fits_file 
path = "/home/homanj/Documents/Flares/AltaiPony/Flare Data/2/kplr010002792-2009259160929_llc.fits"
flc = from_fits_file(path)
```
I get an error message that flc.detrended_flux is not a proper input for np.isfinite. 
#### What is the goal / expected behaviour?

I expected that the program would run smoothly. I also copied the code from from_fits_file in altaipony.lcio and ran each of the parts directly, which resulted in the improper input error message for both fits files (the example one and the downloaded one, which is consistent with the above error)

**Comment by ekaterinailin** [comment]
This should not have been fixed, and now work like this:

`from altaipony.lcio import from_path`
`flc = from_path(path, mode="LC", mission="Kepler")`

Let me know how that goes and sorry for the long waiting time!

**Comment by dPulsar** [comment]
Sorry for the late reply. Thanks for your help and I’ll let you know if I run into issues!

J. Homan

**Comment by ekaterinailin** [comment]
Okay, I'll close it for now!
