### ISSUE TITLE
How to use AltaiPony with TESS tpfs?

### ISSUE THREAD

**Issue by tcjansen** [ekaterinailin/AltaiPony#50]
Hi, 

I'm trying to use this package with TESS target pixel files but have been having some trouble. Specifically, `from_KeplerLightCurve` doesn't seem to like some of the TESS fits headers (probably because it's not a Kepler light curve...):

```
Traceback (most recent call last):
  File "flare_counting.py", line 6, in <module>
    flc = from_TargetPixel_source("TIC 219152539", mission="TESS", sector=5)
  File "//anaconda/lib/python3.5/site-packages/altaipony-0.0.1-py3.5.egg/altaipony/lcio.py", line 59, in from_TargetPixel_source
    lc = from_KeplerLightCurve(lc, origin = 'TPF', **keys)
  File "//anaconda/lib/python3.5/site-packages/altaipony-0.0.1-py3.5.egg/altaipony/lcio.py", line 122, in from_KeplerLightCurve
    flux_unit = u.electron/u.s, **z)
TypeError: __init__() got an unexpected keyword argument 'ccd'
```

Is there a way around this, or perhaps a short tutorial on using altaipony with TESS data?
Thanks!

**Comment by ekaterinailin** [comment]
Hi, I think this problem is solved now: Can you try this [notebook](https://github.com/ekaterinailin/AltaiPony/blob/master/notebooks/TESS_Light_Curves_With_Flares.ipynb) an let me know if it works. You'll need to change the parameter ``mode="LC"`` to mode ``mode="TPF"``. Let me know how it goes :)
