### ISSUE TITLE
TESS notebook "TESS_Light_Curves_With_Flares.ipynb"

### ISSUE THREAD

**Issue by aaronmaas** [ekaterinailin/AltaiPony#54]
While trying the provided notebooks in AltaiPony/notebooks I report an issue with the TESS notebook "TESS_Light_Curves_With_Flares.ipynb". Calling the function _from_mast()_ with the provided TIC example does not work, because the function does not recognize the given ID "29780677". Instead the input has to be "TIC 29780677" and then it will work. 

In code:

flc = from_mast('TIC 29780677', mode="LC", c=2, mission="TESS") instead of  flc = from_mast("29780677", mode="LC", c=2, mission="TESS") 

Cheers

**Comment by ekaterinailin** [comment]
Thanks for pointing it out! 

Apparently, lightkurve needs the TIC, EPIC, and KIC identifiers to disambiguate the targets.

I fixed it in the docs and in the notebook. See [this commit](https://github.com/ekaterinailin/AltaiPony/commit/03c98ce5b1b92ed6cad52216ffad8e2f9c5f61ad).

**Comment by Awshesh12** [comment]
I was trying to run the AltaiPony/notebooks/TESS_Light_Curves_With_Flares.ipynb notebook. In the command lcs.detrend(), gives me an error for 'no group keys passed'. I am attaching a screenshot for that.
![Screenshot from 2020-09-08 14-07-50](https://user-images.githubusercontent.com/49802958/92457171-86d0fc00-f1e1-11ea-839e-78a33c45bb68.png)
