### ISSUE TITLE
Append does not merge some information from Light Curves

### ISSUE THREAD

**Issue by JZeldes** [ekaterinailin/AltaiPony#56]
#### What needs to be created or improved?
Currently, the position corrections, detrended flux and error, and flux correction columns are not combined by the append function, leaving mismatched array sizes for the new FLC object. 

#### Can you provide an example?

Using an already existing flc object. 
lc1=flc[:1]
lc2=flc[:200]
lc1=lc1.append(lc2)
lc1.show_properties()

#### What is the goal / expected behaviour?

All of the data from lc2 should be combined, allowing the new object to be detrended and plotted.

**Comment by ekaterinailin** [comment]
Closed for the same reasons as #46
